
tasks:
  - name: Install Python Dependencies
    init: |
      pip install -r requirements.txt
  - name: Copy Jupyter Config
    init: |
      mkdir -p /home/gitpod/.jupyter/
      cp jupyter_lab_config.py /home/gitpod/.jupyter/




vscode:
  extensions:
    - ms-python.python
    - littlefoxteam.vscode-python-test-adapter
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - mechatroner.rainbow-csv
    - eamodio.gitlens
    - KevinRose.vsc-python-indent
    - akosyakov.gitpod-monitor
